# Generated by Django 5.2.16 on 2026-07-13 19:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='attendancelog',
            name='student_name',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
    ]
