# Generated by Django 5.2.16 on 2026-07-14 02:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0002_attendancelog_student_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='LibrarySystemState',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_open', models.BooleanField(default=False)),
            ],
        ),
    ]
