# Generated by Django 5.2.16 on 2026-08-10 02:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0003_librarysystemstate'),
    ]

    operations = [
        migrations.AddField(
            model_name='attendancelog',
            name='phone_number',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
